FROM rocker/r-ver:4.1.1
CMD ["bash"]
WORKDIR /tmp
RUN apt-get update && \
apt-get install -y python3-dev python3-pip python3-setuptools r-base r-base-dev r-base-core && \
apt-get clean && pip3 install --upgrade pip && pip install biopython pandas numpy 

RUN install2.r --error \
    ggplot2 \
    optparse \
    ggplot2 \
    pheatmap \
    ggfortify \
    dplyr \
    tidyr \
    Rmisc
#RUN R -e "install.packages('BiocManager', 'optparse', 'ggplot2', 'pheatmap', 'ggfortify', 'dplyr', 'tidyr', 'tidyverse', 'rmarkdown', 'RColorBrewer'), dependencies=TRUE, repos='http://cran.rstudio.com/')"
#RUN R -e "install.packages('optparse', dependencies=TRUE, repos='http://cran.rstudio.com/')"
#RUN R -e "install.packages('ggplot2', dependencies=TRUE, repos='http://cran.rstudio.com/')"
#RUN R -e "install.packages('pheatmap', dependencies=TRUE, repos='http://cran.rstudio.com/'); if (!library(pheatmap, logical.return=T)) quit(status=10)"
#RUN R -e "install.packages('ggfortify', dependencies=TRUE, repos='http://cran.rstudio.com/'); if (!library(ggfortify, logical.return=T)) quit(status=10)"
#RUN R -e "install.packages('dplyr', dependencies=TRUE, repos='http://cran.rstudio.com/'); if (!library(dplyr, logical.return=T)) quit(status=10)"
#RUN R -e "install.packages('tidyr', dependencies=TRUE, repos='http://cran.rstudio.com/'); if (!library(tidyr, logical.return=T)) quit(status=10)"