FROM informationsea/bioconda:3
RUN conda install -c bioconda longshot==v0.3.5

FROM rocker/r-ver:4.1.1


#Install library dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    wget \
    zlib1g \
    zlib1g-dev \
    libc6 \
    zlib1g \
    liblzo2-dev \
    libbz2-dev \
    bowtie \
    libncurses-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    samtools \
    minimap2 \
    libxml2-dev \ 
    libglu1 \
    libglpk-dev \
    texlive \ 
    pandoc \
    python3-dev \
    m4 \
    python3-pip \
    python3-setuptools \
    libjpeg-dev \
    && apt-get clean && pip3 install --upgrade pip && pip install matplotlib pandas numpy biopython

RUN R -e "install.packages(c('BiocManager', 'optparse', 'ggplot2', 'methods', 'magrittr', 'swne', 'fs', 'DT', 'gridExtra', 'Seurat', 'heatmap3', 'installr', 'reshape', 'tidyr', 'tidyverse', 'rmarkdown', 'RColorBrewer', 'plotly', 'msigdbr','ggrepel', 'directlabels', 'DT', 'karyoploteR', 'flexdashboard', 'heatmaply', 'statmod', 'optparse'), dependencies=TRUE, repos='http://cran.rstudio.com/')"

RUN R -e "BiocManager::install(c('Limma', 'edgeR', 'ChIPseeker', 'soGGi', 'rGREAT', 'Rsamtools', 'rtracklayer', 'MotifDb', 'tracktables', 'Biostrings', 'Rsubread', 'tximport', 'ChIPQC', 'EBSeq', 'blockmodeling', 'digest', 'DESeq2', 'biomaRt', 'gage', 'pathview', 'affy', 'sva', 'rgl', 'clusterProfiler', 'WGCNA', 'GenomicAlignments', 'GenomicRanges', 'org.Hs.eg.db', 'org.Mm.eg.db', 'TxDb.Hsapiens.UCSC.hg38.knownGene'))"

##############
 ## Clean up
##############
RUN cd / && \
   rm -rf /tmp/* && \
   apt-get autoremove -y && \
   apt-get autoclean -y && \
   rm -rf /var/lib/apt/lists/* && \
   apt-get clean

WORKDIR /