FROM sam16711/crispy3:latest

CMD ["bash"]
RUN apt-get update && \
apt-get install -y r-base r-base-dev r-base-core && \
apt-get clean
#RUN R -e "install.packages(c('BiocManager', 'optparse', 'ggplot2', 'pheatmap', 'ggfortify', 'dplyr', 'tidyr', 'tidyverse', 'rmarkdown', 'RColorBrewer'), dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('optparse', dependencies=TRUE)"
RUN R -e "install.packages('pheatmap', dependencies=TRUE)"
RUN R -e "install.packages('ggfortify', dependencies=TRUE)"
RUN R -e "install.packages('dplyr', dependencies=TRUE)"
RUN R -e "install.packages('tidyr', dependencies=TRUE)"
RUN R -e "install.packages('rmarkdown', dependencies=TRUE)"
RUN R -e "install.packages('RColorBrewer', dependencies=TRUE)"