FROM debian:stable-slim
CMD ["bash"]
WORKDIR /tmp
RUN apt-get update && \
apt-get install -y subread bowtie samtools cutadapt python3-dev python3-pip python3-setuptools r-base r-base-dev r-base-core python3-pandas python3-numpy python3-biopython && \
apt-get clean